### ISSUE TITLE
make help - terminal error 

### ISSUE THREAD

**Issue by sahinakyol** [vmware-tanzu/secrets-manager#453] opened 2024-01-25 23:46 UTC
**Problem:**
When I execute the command make help, my terminal becomes unresponsive. It seems to be attempting to run vim. Here's a screenshot for reference:

<img width="488" alt="Screenshot 2024-01-26 at 12 22 20 AM" src="https://github.com/vmware-tanzu/secrets-manager/assets/6798288/61104e39-b76f-488b-85e1-ec0b78cc8f0d">

**Proposed Solution:**
Using apostrophe instead of backtick.
`@echo "If you are on the build server, stop the cronjob first: 'crontab -e'"`
`@echo "Or 'sudo service cron stop'"`

**Comment by v0lkan** [comment] 2024-01-29 02:44
Strange. this should be a regression. 

Thanks for reporting @sahinakyol .

**Comment by v0lkan** [comment] 2024-01-29 07:13
Addded to the backlog of this iteration.

**Comment by v0lkan** [comment] 2024-01-30 05:09
@sahinakyol would you like to create a PR for this?

When you escape the backticks with a backslash, it works just fine.

```bash
	@echo "If you are on the build server, stop the cronjob first: \`crontab -e\`"
	@echo "Or \`sudo service cron stop\`"
```

Needs to be done for both `make h`, and `make help`?

I’m assigning it to you as a low-hanging first-time commit :). 

Let me know if you don’t want it, and I can fix it myself, too.

Cheers.

**Comment by v0lkan** [comment] 2024-01-30 22:56
Closing this since we merged the change.

**Closed by v0lkan** 2024-01-30 22:56 UTC
Labels: bug, good first issue, regression
